# Generated by Django 5.1.1 on 2024-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_entry_options_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='entry_documents/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='entry_videos/'),
        ),
    ]
