# Generated by Django 5.1.1 on 2024-10-04 13:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entry_document_entry_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='entry_documents/', validators=[api.models.validate_file_size, api.models.validate_document_type]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entry_images/', validators=[api.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='entry_videos/', validators=[api.models.validate_file_size, api.models.validate_video_type]),
        ),
    ]
