# Generated by Django 5.1.1 on 2024-10-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_entry_document_alter_entry_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
