# Generated by Django 5.1.1 on 2024-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('excited', 'Excited'), ('tired', 'Tired')], max_length=10),
        ),
    ]
