# Generated by Django 5.1.1 on 2024-11-15 12:18

from django.db import migrations

def add_unique_email_constraint(apps, schema_editor):
    # Get the User model from the auth app
    User = apps.get_model('auth', 'User')
    
    # Execute the SQL to add a unique constraint on the email field
    schema_editor.execute('''
        ALTER TABLE auth_user
        ADD CONSTRAINT unique_email UNIQUE (email);
    ''')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_entry_mood'),  # Your previous migration
    ]

    operations = [
        migrations.RunPython(add_unique_email_constraint),
    ]
