# Generated by Django 5.1.1 on 2025-02-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('excited', 'Excited'), ('tired', 'Tired'), ('angry', 'Angry'), ('stressed', 'Stressed'), ('shocked', 'Shocked'), ('calm', 'Calm'), ('confused', 'Confused'), ('loved', 'Loved')], default='neutral', max_length=10),
            preserve_default=False,
        ),
    ]
