# Generated by Django 5.1.1 on 2025-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_entry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10, null=True),
        ),
    ]
