# Generated by Django 5.1.1 on 2025-04-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_entry_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='document',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='voice_note',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
